openapi: 3.1.0
x-stoplight:
  id: glh2qbtpwjdxa
info:
  title: price-api
  version: '1.0'
  contact:
    name: Luis Ogando
    email: logando1193@gmail.com
  summary: Test Java / Gradle / Spring Boot (version 3) application.
servers:
  - url: 'http://localhost:8080'
paths:
  /price:
    get:
      summary: GET price
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: get-price
      description: get price entry by params
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: ''
      parameters:
        - schema:
            type: integer
          in: query
          name: product_id
          description: Product code identifier.
          required: true
        - schema:
            type: string
          in: query
          description: Foreign key of the group company
          name: brand_id
          required: true
        - schema:
            type: string
            format: date
            example: '2020-06-15T00:00:00'
          in: query
          name: date
          description: Request date
          required: true
components:
  schemas:
    PriceResponse:
      title: PriceResponse
      x-stoplight:
        id: qi7oreweih1v2
      type: object
      properties:
        product_id:
          type: integer
        brand_id:
          type: integer
        price_list:
          type: integer
        start_date:
          type: string
          format: date
          example: '2020-06-15T00:00:00'
        end_date:
          type: string
          format: date
          example: '2020-06-15T00:00:00'
        price:
          type: number
          format: double
      description: price response
